name: Parsers test for PRs

on:
    workflow_dispatch:
    pull_request:
        paths:
            - 'src/main/kotlin/org/koitharu/kotatsu/parsers/**'

permissions:
    contents: read

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout repository 🌏
            uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

        -   name: Set up enviroment 🔧
            uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
            with:
                java-version: '21'
                distribution: 'temurin'

        -   name: Set up Gradle 📦
            uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a # v4.4.3

        -   name: Compile parsers 🚀
            run: ./gradlew compileKotlin
